version: '3.9'
services:
  ambassador-backend:
    build: .
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - "8003:8000"
    depends_on:
      - ambassador-db
      - redis
    networks:
      - ambassador
      - users

  ambassador-queue:
    build: .
    command: >
      sh -c "python manage.py wait_for_db &&
             python consumer.py"
    restart: always
    env_file:
      - .env
    depends_on:
      - ambassador-db
    networks:
      - ambassador

  ambassador-db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: ambassador
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - .dbdata:/var/lib/mysql
    networks:
      - ambassador

  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - ambassador

networks:
  ambassador:
  users:
    external: true
    name: users