version: '3.9'
services:
  checkout_backend:
    build: .
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8004:8000"
    depends_on:
      - checkout_db
    networks:
      - checkout
      - users

  checkout_queue:
    build: .
    command: >
      sh -c "python manage.py wait_for_db &&
             python consumer.py"
    restart: always
    depends_on:
      - checkout_db
    networks:
      - checkout

  checkout_db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: checkout
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - .dbdata:/var/lib/mysql
    networks:
      - checkout

networks:
  checkout:
  users:
    external: true
    name: users