version: '3'
services:
  checkout-backend:
    build: .
    image: ambassador-microservice/checkout:0.0.1
    env_file:
      - .env
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8004:8000"

  checkout-queue:
    build: .
    image: ambassador-microservice/checkout:0.0.2
    env_file:
      - .env
    command: >
      sh -c "python manage.py wait_for_db &&
             python consumer.py"
