version: '3'
services:
  admin-backend:
    build: .
    image: ambassador-microservice/admin:0.0.2
    env_file:
      - .env
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8002:8000"

  admin-queue:
    build: .
    image: ambassador-microservice/admin:0.0.2
    env_file:
      - .env
    command: >
      sh -c "python manage.py wait_for_db &&
             python consumer.py"

