version: '3.9'
services:
  users-backend:
    build: .
    container_name: users-ms
    volumes:
      - .:/app
    ports:
      - "8001:8000"
    depends_on:
      - users-db
    networks:
      - users

  users-db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: users
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - .dbdata:/var/lib/mysql
    networks:
      - users

networks:
  users:
    name: users